/**
 * Document pipeline — extracts questions and REAL flashcards from uploaded lessons.
 * Flashcards are extracted from the source document text, NOT generated by AI.
 * AI embeddings are optional and non-blocking.
 */
import crypto from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { createAdminClient, requireAdmin } from "@/lib/supabase/server";
import { embed } from "@/lib/ai/engine";
import { extractPdfTextFromBuffer } from "@/lib/ai/pdf";
import { createMedicalKnowledgePipeline } from "@/lib/ai/pipeline";
import { indexSource } from "@/lib/ai/rag";
import { extractLessonIndexText } from "@/lib/ai/source-text";
import { extractQuestionsFromImportedSource } from "@/lib/ai/question-import";
import { extractFlashcardsFromText } from "@/lib/import/flashcard-extract";
import { detectIfomSubject, detectTopic } from "@/lib/ai/ifom";

export const runtime = "nodejs";
export const maxDuration = 120;

type LessonRow = {
  id: string;
  title: string;
  kind: string;
  html_body?: string | null;
  storage_path?: string | null;
  meta?: Record<string, unknown> | null;
};

type PipelineRequest = {
  lesson_id?: string;
  exam_code?: string;
  question_count?: number;
  flashcard_count?: number;
  difficulty?: string;
};

type LessonSource = {
  indexedText: string;
  rawText: string;
  rawHtml: string;
};

async function loadLessonSource(lesson: LessonRow, admin: ReturnType<typeof createAdminClient>): Promise<LessonSource> {
  const isHtmlKind = (k: string) => k === "html" || k === "html-file" || k === "html-inline";

  // Inline HTML (html-inline or html with html_body set)
  if (isHtmlKind(lesson.kind) && lesson.html_body) {
    return {
      indexedText: extractLessonIndexText(lesson),
      rawText: lesson.html_body,
      rawHtml: lesson.html_body,
    };
  }

  if (!lesson.storage_path) {
    const fallback = extractLessonIndexText(lesson);
    return { indexedText: fallback, rawText: fallback, rawHtml: "" };
  }

  const { data } = await admin.storage.from("lesson-assets").download(lesson.storage_path);
  if (!data) {
    const fallback = extractLessonIndexText(lesson);
    return { indexedText: fallback, rawText: fallback, rawHtml: "" };
  }

  // HTML uploaded file (kind = "html", "html-file", "html-inline")
  if (isHtmlKind(lesson.kind)) {
    const html = await data.text();
    return {
      indexedText: extractLessonIndexText(lesson, html),
      rawText: html,
      rawHtml: html,
    };
  }

  if (lesson.kind === "pdf") {
    const pdfText = await extractPdfTextFromBuffer(Buffer.from(await data.arrayBuffer()));
    return {
      indexedText: extractLessonIndexText({ ...lesson, meta: { ...(lesson.meta ?? {}), extracted_text: pdfText } }),
      rawText: pdfText,
      rawHtml: "",
    };
  }

  const fallback = extractLessonIndexText(lesson);
  return { indexedText: fallback, rawText: fallback, rawHtml: "" };
}

async function cleanupPriorGeneratedContent(admin: ReturnType<typeof createAdminClient>, lessonId: string) {
  const { data: existingQuestions } = await admin.from("questions").select("id").eq("lesson_id", lessonId).eq("ai_generated", true);
  const questionIds = (existingQuestions ?? []).map(row => row.id).filter(Boolean);
  if (questionIds.length) {
    await admin.from("question_evidence").delete().in("question_id", questionIds);
    await admin.from("generated_questions").delete().in("question_id", questionIds);
    await admin.from("rag_chunks").delete().eq("source_type", "question").in("source_id", questionIds);
    await admin.from("questions").delete().in("id", questionIds);
  }

  const { data: existingFlashcards } = await admin.from("flashcards").select("id").eq("lesson_id", lessonId).eq("ai_generated", true);
  const flashcardIds = (existingFlashcards ?? []).map(row => row.id).filter(Boolean);
  if (flashcardIds.length) {
    await admin.from("generated_flashcards").delete().in("flashcard_id", flashcardIds);
    await admin.from("rag_chunks").delete().eq("source_type", "flashcard").in("source_id", flashcardIds);
    await admin.from("flashcards").delete().in("id", flashcardIds);
  }
}

export async function POST(req: NextRequest) {
  const ctx = await requireAdmin();
  if (!ctx) return NextResponse.json({ error: "forbidden" }, { status: 403 });

  const {
    lesson_id,
    exam_code = "IFOM_CSE",
    question_count = 20,
    flashcard_count = 20,
    difficulty = "intermediate",
  } = (await req.json()) as PipelineRequest;

  if (!lesson_id) return NextResponse.json({ error: "lesson_id required" }, { status: 400 });

  const admin = createAdminClient();
  const { data: lesson, error: lessonError } = await admin.from("lessons").select("*").eq("id", lesson_id).single();
  if (lessonError || !lesson) return NextResponse.json({ error: "lesson not found" }, { status: 404 });

  const source = await loadLessonSource(lesson as LessonRow, admin);
  const rawIndexText = source.indexedText.trim();
  if (!rawIndexText) return NextResponse.json({ error: "no extractable text in this document" }, { status: 400 });

  const pipeline = createMedicalKnowledgePipeline(rawIndexText);

  await cleanupPriorGeneratedContent(admin, lesson_id);
  await admin.from("source_documents").delete().eq("lesson_id", lesson_id).eq("exam_code", exam_code);

  const subject = detectIfomSubject(rawIndexText);
  const topic = detectTopic(rawIndexText, subject);

  const { data: sourceDocument, error: sourceError } = await admin
    .from("source_documents")
    .insert({
      lesson_id,
      title: lesson.title,
      exam_code,
      subject_title: subject,
      topic_title: topic,
      source_kind: lesson.kind,
      status: "processing",
      extracted_text: pipeline.cleanedText,
      created_by: ctx.user.id,
      meta: {
        imported_from: "document-pipeline",
        section_count: pipeline.sections.length,
      },
    })
    .select()
    .single();

  if (sourceError || !sourceDocument) {
    return NextResponse.json({ error: sourceError?.message || "failed to create source document" }, { status: 500 });
  }

  // Store knowledge chunks with optional embeddings
  const documentChunks = pipeline.chunks.map((content, chunk_index) => ({
    source_document_id: sourceDocument.id,
    chunk_index,
    content,
    content_hash: crypto.createHash("sha1").update(content).digest("hex"),
  }));

  if (documentChunks.length) {
    const { data: insertedChunks, error: chunkError } = await admin
      .from("document_chunks")
      .insert(documentChunks)
      .select("id,chunk_index");

    if (!chunkError && insertedChunks?.length) {
      try {
        const vectors = await embed(pipeline.chunks);
        const embeddings = insertedChunks.map(row => ({
          document_chunk_id: row.id,
          embedding: vectors[row.chunk_index] as never,
          embedding_model: "local-1536",
        }));
        if (embeddings.length) await admin.from("chunk_embeddings").insert(embeddings);
      } catch {
        // embeddings are optional — continue
      }
    }
  }

  // Optional RAG index
  try {
    await admin.from("rag_chunks").delete().eq("source_type", "lesson").eq("source_id", lesson.id);
    await indexSource("lesson", lesson.id, pipeline.cleanedText);
  } catch {
    // RAG indexing optional
  }

  // Extract questions from the raw document text (no AI — regex-based)
  const questionDrafts = question_count > 0
    ? extractQuestionsFromImportedSource(source.rawText, {
        preferredDifficulty: difficulty,
        count: question_count,
        lessonId: lesson.id,
        rawHtml: source.rawHtml,
      })
    : [];

  // Extract REAL flashcards from the source text (no AI — text extraction engine)
  const flashcardDrafts = flashcard_count > 0
    ? extractFlashcardsFromText(source.rawText || source.rawHtml, {
        isHtml: Boolean(source.rawHtml),
        maxCards: flashcard_count,
        tags: [exam_code.replaceAll("_", " "), subject, topic].filter(Boolean),
      })
    : [];

  let insertedQuestions = 0;
  let insertedFlashcards = 0;

  if (questionDrafts.length) {
    const rows = questionDrafts.map(item => ({
      lesson_id,
      stem: item.stem,
      choices: item.choices,
      answer_key: item.answer_key,
      explanation: item.explanation,
      difficulty: item.difficulty || difficulty,
      tags: Array.from(new Set([
        exam_code.replaceAll("_", " "),
        item.subject || subject,
        item.system || item.subject || subject,
        item.topic || topic,
        ...(Array.isArray(item.tags) ? item.tags : []),
      ].filter(Boolean))),
      image_path: item.image_path || null,
      image_caption: item.image_caption || null,
      ai_generated: false,
      created_by: ctx.user.id,
    }));

    const { data: inserted, error } = await admin.from("questions").insert(rows).select("id");
    if (!error) insertedQuestions = inserted?.length ?? rows.length;
  }

  if (flashcardDrafts.length) {
    const rows = flashcardDrafts.map(card => ({
      lesson_id,
      front: card.front,
      back: card.back,
      tags: card.tags,
      ai_generated: false,
      created_by: ctx.user.id,
    }));

    const { data: inserted, error } = await admin.from("flashcards").insert(rows).select("id");
    if (!error) insertedFlashcards = inserted?.length ?? rows.length;
  }

  await admin
    .from("source_documents")
    .update({
      status: "ready",
      chunk_count: pipeline.chunks.length,
      processed_at: new Date().toISOString(),
      meta: {
        imported_from: "document-pipeline",
        section_count: pipeline.sections.length,
        question_count: insertedQuestions,
        flashcard_count: insertedFlashcards,
      },
    })
    .eq("id", sourceDocument.id);

  return NextResponse.json({
    document: {
      id: sourceDocument.id,
      title: lesson.title,
      subject_title: subject,
      topic_title: topic,
      chunk_count: pipeline.chunks.length,
      section_count: pipeline.sections.length,
      question_count: insertedQuestions,
      flashcard_count: insertedFlashcards,
      status: "ready",
    },
  });
}
