const STOP = new Set(["the","and","for","with","that","this","from","have","been","into","your","their","than","then","were","which","patient","patients","clinical","most","likely","following","because","after","before","during","between","within"]);
export const IFOM_CSE_SUBJECTS = ["Dermatology","Infectious Diseases","Respiratory System","Renal & Urogenital","Rheumatology & Orthopedics","Hematology","Endocrine","Cardiology","Neurology","Gastrointestinal System","Obstetrics","Gynecology","Pediatrics","Psychiatry","Biostatistics"] as const;
const SUBJECT_KEYWORDS: Record<(typeof IFOM_CSE_SUBJECTS)[number], string[]> = {
  "Dermatology": ["skin","rash","psoriasis","eczema","melanoma","urticaria","dermat","bullous"],
  "Infectious Diseases": ["infection","infectious","antibiotic","sepsis","fever","viral","bacterial","fungal","tuberculosis","hiv"],
  "Respiratory System": ["lung","asthma","copd","pneumonia","respiratory","pulmonary","pleural","oxygen","ventilation"],
  "Renal & Urogenital": ["renal","kidney","neph","urinary","bladder","ureter","prostate","hematuria","proteinuria"],
  "Rheumatology & Orthopedics": ["joint","arthritis","bone","fracture","gout","lupus","rheumatoid","orthopedic","muscle"],
  "Hematology": ["anemia","hemoglobin","platelet","coagulation","bleeding","leukemia","lymphoma","hematology"],
  "Endocrine": ["diabetes","thyroid","pituitary","adrenal","hormone","endocrine","insulin","cortisol"],
  "Cardiology": ["cardiac","heart","arrhythmia","ecg","myocardial","hypertension","valve","murmur","cardiology"],
  "Neurology": ["seizure","stroke","neurologic","brain","cranial","neurology","neuropathy","meningitis"],
  "Gastrointestinal System": ["gastrointestinal","gastro","gastric","stomach","intestin","bowel","colon","rectal","rectum","hepatic","liver","pancreas","pancreatic","biliary","bile","esophagus","esophageal","diarrhea","constipation","colitis","crohn","ibd","gerd","peptic","ulcer","hepatitis","cirrhosis","jaundice","gi tract","colorectal","malabsorption","celiac","vomiting","nausea","dysphagia","hemorrhoid","appendix","appendicitis"],
  "Obstetrics": ["pregnancy","pregnant","obstetric","antenatal","labor","delivery","postpartum","fetal","maternal","placenta","pre-eclampsia","obgyn","obs"],
  "Gynecology": ["gyne","gyn","gynecology","gynecologic","uterus","ovary","ovarian","menstrual","pelvic","cervix","cervical","contraception","infertility","obgyn"],
  "Pediatrics": ["child","infant","newborn","pediatric","adolescent","vaccination","developmental"],
  "Psychiatry": ["depression","anxiety","psychosis","psychiatric","mania","schizophrenia","suicide"],
  "Biostatistics": ["sensitivity","specificity","prevalence","incidence","risk","odds","trial","confidence interval","biostatistics"],
};
function tokenize(input: string) { return input.toLowerCase().replace(/[^\p{L}\p{N}\s-]+/gu, " ").split(/\s+/).map((t) => t.trim()).filter(Boolean); }
export function detectIfomSubject(input: string) { const text = input.toLowerCase(); const ranked = IFOM_CSE_SUBJECTS.map((subject) => ({ subject, score: SUBJECT_KEYWORDS[subject].reduce((sum, keyword) => sum + (text.includes(keyword) ? 1 : 0), 0) })).sort((a, b) => b.score - a.score); return ranked[0]?.score ? ranked[0].subject : "Infectious Diseases"; }
export function detectDifficulty(input: string, preferred = "intermediate") { const text = input.toLowerCase(); const complexity = (text.match(/however|except|despite|although|best next step|most appropriate|contraindicat|interpret/gi)?.length ?? 0) + (text.length > 420 ? 2 : text.length > 260 ? 1 : 0); if (["foundation","intermediate","advanced","expert"].includes(preferred)) return preferred; if (complexity >= 4) return "expert"; if (complexity >= 3) return "advanced"; if (complexity >= 2) return "intermediate"; return "foundation"; }
export function detectTopic(input: string, fallbackSubject?: string) { const counts = new Map<string, number>(); for (const token of tokenize(input)) { if (token.length < 4 || STOP.has(token)) continue; counts.set(token, (counts.get(token) || 0) + 1); } const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([token]) => token); if (top.length) return top.map((t) => t[0].toUpperCase() + t.slice(1)).join(" / "); return fallbackSubject || "General Principles"; }
export function extractEvidenceSentences(input: string, count = 6) { const sentences = input.replace(/\s+/g, " ").split(/(?<=[\.!?])\s+|\n+/).map((l) => l.trim()).filter((l) => l.length >= 50); if (!sentences.length) return [input.replace(/\s+/g, " ").trim()].filter(Boolean); return sentences.sort((a, b) => b.length - a.length).slice(0, Math.max(count * 2, 10)).sort((a, b) => a.length - b.length).slice(0, count); }
function buildChoices(correct: string, pool: string[]) { const keys = ["A","B","C","D","E"]; const distractors = pool.filter((x) => x !== correct).slice(0, 4); while (distractors.length < 4) distractors.push(`Unsupported alternative ${distractors.length + 1}`); return [correct, ...distractors].slice(0, 5).map((text, index) => ({ key: keys[index], text })); }
export function generateIfomQuestionDrafts(sourceText: string, count = 5, preferredDifficulty = "intermediate") { const subject = detectIfomSubject(sourceText); const topic = detectTopic(sourceText, subject); const evidence = extractEvidenceSentences(sourceText, Math.max(count, 8)); const difficulty = detectDifficulty(sourceText, preferredDifficulty); return evidence.slice(0, count).map((sentence) => { const explanation = sentence.replace(/\s+/g, " ").trim(); const pool = evidence.map((item) => item.replace(/\s+/g, " ").trim().slice(0, 140)); const correct = explanation.slice(0, 140); return { stem: `A learner reviewing ${subject} for IFOM CSE wants the statement best supported by the imported source. Which option is the best match for ${topic}?`, choices: buildChoices(correct, pool), answer_key: "A", explanation, difficulty, tags: ["IFOM CSE", subject, topic, difficulty], exam: "IFOM_CSE", subject, topic, evidence_text: explanation, evidence_start: Math.max(sourceText.indexOf(explanation), 0), evidence_end: Math.max(sourceText.indexOf(explanation), 0) + explanation.length }; }); }
export function generateIfomFlashcardDrafts(sourceText: string, count = 10) { const subject = detectIfomSubject(sourceText); const topic = detectTopic(sourceText, subject); const evidence = extractEvidenceSentences(sourceText, Math.max(count, 10)); return evidence.slice(0, count).map((sentence, index) => ({ front: `${subject}: High-yield point ${index + 1}`, back: [`High-Yield: ${sentence}`, `Clinical Pearl: Focus on ${topic.toLowerCase()} when solving IFOM CSE vignettes.`, `Learn More: Review the imported source evidence for the exact wording and context.`].join("\n\n"), tags: ["IFOM CSE", subject, topic], exam: "IFOM_CSE", subject, topic, evidence_text: sentence })); }
