import { AI_ENABLED, chat, TUTOR_SYSTEM } from "./engine";
import { retrieve } from "./rag";
import { generateIfomFlashcardDrafts, generateIfomQuestionDrafts } from "./ifom";
type HistoryMessage = { role: "user" | "assistant"; content: string };
type TutorOptions = { history?: HistoryMessage[]; mode?: "tutor" | "exam"; lessonTitle?: string; lessonContext?: string; companionNotes?: string; };
type CitationOut = { n: number; source_type: string; source_id: string; title: string; source_label: string; lesson_kind?: string | null; };
function compact(input: string, max = 6000) { return input.replace(/\s+/g, " ").trim().slice(0, max); }
function pickSentences(input: string, max = 14) { return input.replace(/\s+/g, " ").split(/(?<=[\.!؟?])\s+|\n+/).map((s) => s.trim()).filter((s) => s.length >= 35).slice(0, max); }
function localSummary(sourceText: string, max = 8) { const points = pickSentences(sourceText, max); if (!points.length) return [compact(sourceText || "No usable lesson text found.", 240)]; return points; }
export async function tutorAnswer(question: string, options: TutorOptions = {}) { const history = options.history ?? []; const mode = options.mode ?? "tutor"; const ctx = await retrieve(question, 8); const citations: CitationOut[] = ctx.map((c, i) => ({ n: i + 1, source_type: c.source_type, source_id: c.source_id, title: c.title, source_label: c.source_label, lesson_kind: c.lesson_kind ?? null })); const ragContext = ctx.map((c, i) => `[[${i + 1}]] ${c.source_label}: ${c.title}${c.lesson_kind ? ` (${c.lesson_kind})` : ""}\n${c.content}`).join("\n\n"); const localContext = [options.lessonTitle ? `LESSON TITLE: ${options.lessonTitle}` : "", options.lessonContext ? `LESSON CONTEXT:\n${compact(options.lessonContext)}` : "", options.companionNotes ? `STUDENT NOTES:\n${compact(options.companionNotes, 3000)}` : ""].filter(Boolean).join("\n\n"); if (!AI_ENABLED) { const sourcePool = [localContext, ragContext].filter(Boolean).join("\n\n"); const bullets = localSummary(sourcePool || question, 5); const answer = [mode === "exam" ? "Exam-style answer from the indexed platform content:" : "Answer from the indexed platform content:", ...bullets.map((line, idx) => `${idx + 1}. ${line}`), citations.length ? `\nReferenced sources: ${citations.map((c) => `[[${c.n}]] ${c.title}`).join(" · ")}` : "\nNo indexed source matched strongly enough; answer is based on local lesson text only."].join("\n"); return { answer, citations }; } const modeInstruction = mode === "exam" ? "EXAM MODE: coach like an examiner. Start with the key clues, challenge the student to commit to an answer when appropriate, then explain why the final answer is correct and why the alternatives are weaker." : "TUTOR MODE: answer directly, teach step-by-step, and keep the explanation practical."; const messages = [{ role: "system" as const, content: TUTOR_SYSTEM }, { role: "system" as const, content: `${modeInstruction}\nCONTEXT PRIORITY: Attached lesson context > student notes > Question Bank > HTML Lessons > PDF Lessons > Flashcards > Notes. Use available context first and cite sources as [[n]]. If context is insufficient, say so clearly.\n\nLOCAL CONTEXT:\n${localContext || "(none)"}\n\nRAG CONTEXT:\n${ragContext || "(none)"}` }, ...history.slice(-10), { role: "user" as const, content: question }]; const answer = await chat(messages, { temperature: mode === "exam" ? 0.15 : 0.2 }); return { answer, citations }; }
export async function generateQuestions(sourceText: string, count = 5, difficulty = "intermediate") { const local = generateIfomQuestionDrafts(sourceText, count, difficulty); if (!AI_ENABLED) return local; const prompt = `Generate ${count} realistic evidence-grounded IFOM CSE / medical single-best-answer questions from the SOURCE.\nReturn JSON: { "questions": [{ "stem": "...", "choices":[{"key":"A","text":"..."},{"key":"B","text":"..."},{"key":"C","text":"..."},{"key":"D","text":"..."},{"key":"E","text":"..."}], "answer_key":"B", "explanation":"...", "difficulty":"${difficulty}", "tags":["IFOM CSE","Subject","Topic"], "subject":"...", "topic":"...", "evidence_text":"..." }] }\nSOURCE:\n${sourceText.slice(0, 12000)}`; const raw = await chat([{ role: "system", content: TUTOR_SYSTEM }, { role: "user", content: prompt }], { temperature: 0.3, json: true }); try { const parsed = JSON.parse(raw).questions ?? []; return parsed.length ? parsed : local; } catch { return local; } }
export async function generateFlashcards(sourceText: string, count = 10) { const local = generateIfomFlashcardDrafts(sourceText, count); if (!AI_ENABLED) return local; const prompt = `Create ${count} high-yield evidence-grounded medical flashcards from the SOURCE.\nReturn JSON: { "cards":[{ "front":"...", "back":"...", "tags":["IFOM CSE","Subject","Topic"], "subject":"...", "topic":"...", "evidence_text":"..." }] }\nBack should be concise and practical.\nSOURCE:\n${sourceText.slice(0, 12000)}`; const raw = await chat([{ role: "system", content: TUTOR_SYSTEM }, { role: "user", content: prompt }], { temperature: 0.3, json: true }); try { const parsed = JSON.parse(raw).cards ?? []; return parsed.length ? parsed : local; } catch { return local; } }
export async function summarize(sourceText: string) { if (!AI_ENABLED) return localSummary(sourceText, 8).map((line) => `• ${line}`).join("\n"); return chat([{ role: "system", content: TUTOR_SYSTEM }, { role: "user", content: `Summarize the following medical lesson in 8 clinical bullet points:\n\n${sourceText.slice(0, 8000)}` }], { temperature: 0.2 }); }
